### ISSUE TITLE
Error running tisdk install

### ISSUE THREAD

**Issue by yankovalera** [dbankier/tisdk#5]
When I try to run the command I get this:

module.js:338
    throw err;
          ^
Error: Cannot find module 'adm-zip'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tisdk/bin/tisdk:9:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

It's because there's a dependancy with adm-zip?

Thanks.

**Comment by m1ga** [comment]
https://github.com/dbankier/tisdk/blob/master/bin/tisdk#L9
needs to be removed, then it's working fine again

**Comment by dbankier** [comment]
just pushed a new release 1.2.1
