### ISSUE TITLE
Error when folder exists

### ISSUE THREAD

**Issue by m1ga** [dbankier/tisdk#6]
I've updated tisdk and tried to install 4.1.0.GA again. Since I already had it installed I got this error when it tried to move the folder at the end:

``` javascript
Renaming /home/user/.titanium/mobilesdk/linux/4.1.0.v20150619182147 to /home/user/.titanium/mobilesdk/linux/4.1.0.GA

fs.js:555
  return binding.rename(pathModule._makeLong(oldPath),
                 ^
Error: ENOTEMPTY, directory not empty '/home/user/.titanium/mobilesdk/linux/4.1.0.GA'
    at Object.fs.renameSync (fs.js:555:18)
    at /home/user/tools/tisdk/bin/tisdk:61:10
    at extractFile [as _onTimeout] (/home/user/tools/tisdk/node_modules/node-appc/lib/zip.js:69:5)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

Perhaps it would be good to check if its already installed and skip everything? Or at least throw an error message "already installed - continue?" and stop or overwrite it

**Comment by dbankier** [comment]
just pushed a new release 1.2.1
