### ISSUE TITLE
Error renaming (linux)

### ISSUE THREAD

**Issue by m1ga** [dbankier/tisdk#9]
building went fine but at the end I got:

```
...
Packaging version (5.0.0) complete
scons: done building targets.

fs.js:555
  return binding.rename(pathModule._makeLong(oldPath),
                 ^
Error: EXDEV, cross-device link not permitted '/tmp/tisdk_24606DZwGRPgpe5hL/dist/mobilesdk-5.0.0-linux.zip'
    at Object.fs.renameSync (fs.js:555:18)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/tisdk/index.js:125:12)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
```

system: linux

**Comment by dbankier** [comment]
Sorry, didn't test against linux. I need to implement the move differently.

(eg: http://stackoverflow.com/questions/4568689/how-do-i-move-file-a-to-a-different-partition-or-device-in-node-js/29287813#29287813)
